@DigimonAPI_HostAddress = http://localhost:5208

GET {{DigimonAPI_HostAddress}}/digimon/
Accept: application/json
###

GET {{DigimonAPI_HostAddress}}/digimon/agumon
Content-Type: application/json
Accept: application/json
###

GET {{DigimonAPI_HostAddress}}/digimon/level/mega
Content-Type: application/json
Accept: application/json
###

GET {{DigimonAPI_HostAddress}}/digimon/search?search=garuru
Content-Type: application/json
Accept: application/json
###